/* Generated by scripts/generate-contracts. */
window.SiteKitCatalog = [
  {
    "slug": "accordion",
    "name": "Accordion",
    "category": "Feedback",
    "description": "A stacked disclosure control for expandable sections.",
    "variants": [
      "faq",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-accordion\" aria-label=\"Accordion\"><details open><summary>What is included?</summary><p>Accessible disclosure behavior with tokenized SiteKit styling.</p></details><details><summary>Can I compose it?</summary><p>Use each item for a single question or grouped detail.</p></details></section>\n"
  },
  {
    "slug": "alert",
    "name": "Alert",
    "category": "Feedback",
    "description": "A status message for success, warning, error, or neutral feedback.",
    "variants": [
      "neutral",
      "compact",
      "danger",
      "warning",
      "success"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<aside class=\"sk-alert\" role=\"status\" data-variant=\"warning\"><strong>Deploy attention</strong><p>Two checks need review before this build can ship.</p></aside>\n"
  },
  {
    "slug": "avatar",
    "name": "Avatar",
    "category": "Data Display",
    "description": "A compact visual identity marker for a person, team, or object.",
    "variants": [
      "initials",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<span class=\"sk-avatar\" ><img alt=\"Alex Morgan\" src=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='white'/%3E%3Cpath d='M16 48V18h32v30H16Z' fill='none' stroke='black' stroke-width='4'/%3E%3Ccircle cx='32' cy='29' r='8' fill='black'/%3E%3Cpath d='M19 48c4-9 10-13 13-13s9 4 13 13' fill='black'/%3E%3C/svg%3E\"></span>\n"
  },
  {
    "slug": "badge",
    "name": "Badge",
    "category": "Data Display",
    "description": "A compact status, category, or metadata label.",
    "variants": [
      "neutral",
      "success",
      "warning",
      "danger",
      "outline"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<span class=\"sk-badge\" data-variant=\"neutral\">Badge</span>\n"
  },
  {
    "slug": "bento-grid",
    "name": "Bento Grid",
    "category": "Content",
    "description": "A square-cornered modular grid for grouped capabilities, proof points, or portfolio services.",
    "variants": [
      "portfolio",
      "balanced",
      "showcase",
      "dense"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-component-container\"><section class=\"sk-bento-grid\" aria-labelledby=\"bento-grid-title\">\n  <div class=\"sk-bento-grid__intro\">\n    <span class=\"sk-badge\" data-variant=\"outline\">Services</span>\n    <div class=\"sk-bento-grid__content\">\n      <h2 id=\"bento-grid-title\">Build systems that stay sharp.</h2>\n      <p>A true bento composition with uneven spans, square panels, and mono titles.</p>\n    </div>\n  </div>\n  <article class=\"sk-bento-grid__item\" data-span=\"wide\">\n    <p class=\"sk-bento-grid__kicker\">01</p>\n    <h3>Custom Apps</h3>\n    <p>Production interfaces, dashboards, and customer workflows with clean component boundaries.</p>\n  </article>\n  <article class=\"sk-bento-grid__item\" data-span=\"tall\">\n    <p class=\"sk-bento-grid__kicker\">02</p>\n    <h3>Security Audits</h3>\n    <p>Focused reviews with remediation paths, checklists, and durable proof.</p>\n  </article>\n  <article class=\"sk-bento-grid__item\">\n    <p class=\"sk-bento-grid__kicker\">03</p>\n    <h3>Plugins</h3>\n    <p>Purpose-built extensions.</p>\n  </article>\n  <article class=\"sk-bento-grid__item\">\n    <p class=\"sk-bento-grid__kicker\">04</p>\n    <h3>Design Systems</h3>\n    <p>Reusable component contracts.</p>\n  </article>\n</section></div>\n"
  },
  {
    "slug": "breadcrumbs",
    "name": "Breadcrumbs",
    "category": "Navigation",
    "description": "A navigational trail that shows the current page location.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<nav class=\"sk-breadcrumbs\" aria-label=\"Breadcrumbs\"><ol><li><a href=\"#home\">Home</a></li><li><a href=\"#components\">Components</a></li><li aria-current=\"page\">Breadcrumbs</li></ol></nav>\n"
  },
  {
    "slug": "button",
    "name": "Button",
    "category": "Actions",
    "description": "A semantic action control for links, form submits, and interface commands.",
    "variants": [
      "primary",
      "secondary",
      "ghost",
      "danger"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<button class=\"sk-button\" type=\"button\" data-variant=\"primary\">Button</button>\n"
  },
  {
    "slug": "card",
    "name": "Card",
    "category": "Content",
    "description": "A bounded content region for a single object, summary, or grouped action.",
    "variants": [
      "plain",
      "interactive",
      "dense"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-card\" aria-labelledby=\"card-title\"><h2 id=\"card-title\">Review changes</h2><p>Semantic HTML, local assets, and reusable styles.</p><div class=\"sk-card__actions\"><button class=\"sk-button\" type=\"button\">Continue</button></div></section>\n"
  },
  {
    "slug": "carousel",
    "name": "Carousel",
    "category": "Data Display",
    "description": "A grouped media or content sequence with explicit navigation controls.",
    "variants": [
      "cards",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-carousel\" aria-labelledby=\"carousel-title\"><h2 id=\"carousel-title\">Featured components</h2><div class=\"sk-carousel__track\" tabindex=\"0\"><article><h3>Card</h3><p>Structured content.</p></article><article><h3>Tabs</h3><p>Switchable panels.</p></article><article><h3>Modal</h3><p>Focused dialog.</p></article></div><div class=\"sk-carousel__controls\"><button class=\"sk-button\" type=\"button\" data-variant=\"secondary\" data-carousel-prev>Prev</button><button class=\"sk-button\" type=\"button\" data-carousel-next>Next</button></div></section>\n"
  },
  {
    "slug": "checkbox",
    "name": "Checkbox",
    "category": "Forms",
    "description": "A binary input that can be checked or unchecked.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-checkbox\"><label><input type=\"checkbox\" checked> Receive release notes</label></div>\n"
  },
  {
    "slug": "checkout-summary",
    "name": "Checkout Summary",
    "category": "Commerce",
    "description": "A commerce order summary with totals, taxes, discounts, and trust metadata.",
    "variants": [
      "default",
      "compact",
      "sticky"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-checkout-summary\" aria-labelledby=\"checkout-summary-title\"><h2 id=\"checkout-summary-title\">Order summary</h2><ul class=\"sk-checkout-summary__items\"><li><span>SiteKit Pro license</span><strong>$99</strong></li><li><span>Priority support</span><strong>$29</strong></li></ul><dl><div><dt>Subtotal</dt><dd>$128</dd></div><div><dt>Tax</dt><dd>$8</dd></div><div data-total><dt>Total</dt><dd>$136</dd></div></dl><div class=\"sk-checkout-summary__actions\"><button class=\"sk-button\" type=\"button\">Checkout</button><button class=\"sk-button\" type=\"button\" data-variant=\"secondary\">Edit cart</button></div></section>\n"
  },
  {
    "slug": "code-block",
    "name": "Code Block",
    "category": "Data Display",
    "description": "A readable code or command block with caption and copy action.",
    "variants": [
      "default",
      "terminal",
      "numbered"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<figure class=\"sk-code-block\"><figcaption><span>HTML example</span><button type=\"button\" data-copy-code>Copy</button></figcaption><pre><code>&lt;button class=\"sk-button\" type=\"button\"&gt;Save&lt;/button&gt;</code></pre></figure>\n"
  },
  {
    "slug": "color-picker",
    "name": "Color Picker",
    "category": "Forms",
    "description": "A native color control with an accessible label.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-color-picker\"><label for=\"color-picker-control\">Accent color</label><input id=\"color-picker-control\" type=\"color\" value=\"#000000\"></div>\n"
  },
  {
    "slug": "combobox",
    "name": "Combobox",
    "category": "Forms",
    "description": "An autocomplete text input paired with suggested options.",
    "variants": [
      "autocomplete",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-combobox\"><label for=\"combobox-input\">Component</label><input id=\"combobox-input\" type=\"text\" role=\"combobox\" aria-controls=\"combobox-options\" aria-expanded=\"true\" value=\"Button\" autocomplete=\"off\"><ul id=\"combobox-options\" role=\"listbox\"><li role=\"option\" aria-selected=\"true\">Button</li><li role=\"option\">Card</li><li role=\"option\">Modal</li></ul></div>\n"
  },
  {
    "slug": "command-strip",
    "name": "Command Strip",
    "category": "Data Display",
    "description": "A compact operational metric strip for status, filters, or system state.",
    "variants": [
      "default",
      "compact",
      "four-up"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<section class=\"sk-command-strip\" aria-label=\"Command Strip\"><span>Version 1.0.0</span><span>Source-vendored</span></section>\n"
  },
  {
    "slug": "content-section",
    "name": "Content Section",
    "category": "Content",
    "description": "A responsive editorial section with copy, actions, and an optional media or proof panel.",
    "variants": [
      "media-right",
      "media-left",
      "centered",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-component-container\"><section class=\"sk-content-section\" aria-labelledby=\"content-section-title\">\n  <div class=\"sk-content-section__copy\">\n    <span class=\"sk-badge\" data-variant=\"outline\">Workflow</span>\n    <h2 id=\"content-section-title\">Build fast, deploy faster.</h2>\n    <p>Use a focused content block when the page needs a deeper argument than a hero or card can carry.</p>\n    <a class=\"sk-button\" href=\"#content-section-title\">Read the guide</a>\n  </div>\n  <figure class=\"sk-content-section__media\">\n    <figcaption>Deploy pipeline</figcaption>\n    <dl>\n      <div><dt>Build</dt><dd>42s</dd></div>\n      <div><dt>Checks</dt><dd>Passing</dd></div>\n      <div><dt>Theme</dt><dd>Tokenized</dd></div>\n    </dl>\n  </figure>\n</section></div>\n"
  },
  {
    "slug": "cta",
    "name": "CTA",
    "category": "Content",
    "description": "A conversion block with a clear next action.",
    "variants": [
      "band",
      "inline",
      "stacked"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-cta\" aria-labelledby=\"cta-title\"><div class=\"sk-cta__inner\"><div class=\"sk-cta__copy\"><h2 id=\"cta-title\">Ship the next page.</h2><p>Compose tokenized sections and move from idea to production.</p></div><div class=\"sk-cta__actions\"><button class=\"sk-button\" type=\"button\">Continue</button></div></div></section>\n"
  },
  {
    "slug": "date-input",
    "name": "Date Input",
    "category": "Forms",
    "description": "A native date input with label and help text.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-date-input\"><label for=\"date-input-control\">Publish date</label><input id=\"date-input-control\" type=\"date\" value=\"2026-07-09\"><p>Use for simple date entry.</p></div>\n"
  },
  {
    "slug": "date-picker",
    "name": "Date Picker",
    "category": "Forms",
    "description": "A compact date-picker surface with a visible calendar grid.",
    "variants": [
      "calendar",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-date-picker\" aria-labelledby=\"date-picker-title\"><label for=\"date-value\">Date (YYYY-MM-DD)</label><input id=\"date-value\" name=\"date\" type=\"date\" value=\"2026-07-09\"><header hidden><button type=\"button\" aria-label=\"Previous month\">Prev</button><h2 id=\"date-picker-title\">Choose a date</h2><button type=\"button\" aria-label=\"Next month\">Next</button></header><div data-weekdays hidden aria-hidden=\"true\"><span>Su</span><span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Sa</span></div><div role=\"grid\" hidden aria-label=\"Calendar\"></div></section>\n"
  },
  {
    "slug": "drawer",
    "name": "Drawer",
    "category": "Overlays",
    "description": "A side panel for secondary navigation or contextual actions.",
    "variants": [
      "right",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<button class=\"sk-button\" type=\"button\" data-sk-drawer-open=\"project-drawer\">Open settings</button><div class=\"sk-drawer-shell\"><div class=\"sk-drawer-scrim\" hidden aria-hidden=\"true\"></div><aside class=\"sk-drawer\" id=\"project-drawer\" data-sk-drawer hidden aria-hidden=\"true\" aria-labelledby=\"drawer-title\"><header><div><h2 id=\"drawer-title\">Project settings</h2><p>Manage the active workspace.</p></div><button class=\"sk-button\" type=\"button\" data-variant=\"secondary\" data-sk-drawer-close aria-label=\"Close drawer\">X</button></header><nav aria-label=\"Drawer\"><a href=\"#profile\">Profile</a><a href=\"#billing\">Billing</a><a href=\"#access\">Access control</a></nav><button class=\"sk-button\" type=\"button\">Save changes</button></aside></div>\n"
  },
  {
    "slug": "dropdown-menu",
    "name": "Dropdown Menu",
    "category": "Actions",
    "description": "A menu button with grouped actions.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-dropdown-menu\"><button class=\"sk-button\" type=\"button\" aria-haspopup=\"menu\" aria-expanded=\"false\">Actions</button><ul role=\"menu\" hidden><li role=\"none\"><button role=\"menuitem\" type=\"button\">Duplicate</button></li><li role=\"none\"><button role=\"menuitem\" type=\"button\">Archive</button></li></ul></div>\n"
  },
  {
    "slug": "ecosystem-map",
    "name": "Ecosystem Map",
    "category": "Data Display",
    "description": "A semantic map of projects, packages, docs, and relationships.",
    "variants": [
      "grid",
      "radial",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-ecosystem-map\" aria-label=\"Source and browser ecosystem\"><article id=\"ecosystem-source\"><h2>Source</h2><p>Tokens and templates.</p></article><article id=\"ecosystem-browser\"><h2>Browser</h2><p>Native HTML and optional enhancements.</p></article><p><a href=\"#ecosystem-source\">Source</a> supplies the <a href=\"#ecosystem-browser\">browser</a>.</p></section>\n"
  },
  {
    "slug": "empty-state",
    "name": "Empty State",
    "category": "Feedback",
    "description": "A clear message for empty collections with optional recovery action.",
    "variants": [
      "default",
      "compact",
      "commerce"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-empty-state\" aria-labelledby=\"empty-state-title\"><span class=\"sk-empty-state__mark\" aria-hidden=\"true\">0</span><h2 id=\"empty-state-title\">No projects yet</h2><p>Create your first project to start collecting tasks, files, and deployment notes.</p><div><button class=\"sk-button\" type=\"button\">Continue</button></div></section>\n"
  },
  {
    "slug": "error-state",
    "name": "Error State",
    "category": "Feedback",
    "description": "A recoverable error message with next steps and support context.",
    "variants": [
      "default",
      "inline",
      "critical"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-error-state\" aria-labelledby=\"error-state-title\"><span data-error-code>Sync failed</span><h2 id=\"error-state-title\">We could not save changes.</h2><p>The API returned a recoverable error. Retry the request or review the deployment log.</p><div><button class=\"sk-button\" type=\"button\">Continue</button></div></section>\n"
  },
  {
    "slug": "feature-grid",
    "name": "Feature Grid",
    "category": "Content",
    "description": "A responsive list of capabilities or benefits.",
    "variants": [
      "two-column",
      "three-column",
      "dense"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<section class=\"sk-feature-grid\" aria-label=\"Feature Grid\"><article><span data-feature-icon aria-hidden=\"true\">01</span><h3>Tokenized UI</h3><p>Every surface follows SiteKit theme contracts.</p></article><article><span data-feature-icon aria-hidden=\"true\">02</span><h3>Semantic markup</h3><p>Patterns start from native HTML.</p></article><article><span data-feature-icon aria-hidden=\"true\">03</span><h3>Fast previews</h3><p>Components can be inspected and copied quickly.</p></article></section>\n"
  },
  {
    "slug": "fieldset",
    "name": "Fieldset",
    "category": "Forms",
    "description": "A grouped set of form controls with a legend.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<fieldset class=\"sk-fieldset\"><legend>Contact preference</legend><label><input type=\"radio\" name=\"contact\" checked> Email</label><label><input type=\"radio\" name=\"contact\"> Phone</label></fieldset>\n"
  },
  {
    "slug": "file",
    "name": "File",
    "category": "Forms",
    "description": "A file metadata row for selected or attached files.",
    "variants": [
      "row",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<article class=\"sk-file\"><span aria-hidden=\"true\">DOC</span><div><h3>proposal.pdf</h3><p>248 KB · Ready</p></div><button class=\"sk-button\" type=\"button\" data-variant=\"secondary\">Remove</button></article>\n"
  },
  {
    "slug": "file-upload",
    "name": "File Upload",
    "category": "Forms",
    "description": "A file input drop area with a clear label.",
    "variants": [
      "dropzone",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-file-upload\"><label for=\"file-upload-control\">Upload files</label><input id=\"file-upload-control\" type=\"file\"><p>Choose a local file. Your application owns uploading.</p></div>\n"
  },
  {
    "slug": "footer",
    "name": "Footer",
    "category": "Content",
    "description": "A semantic page footer for navigation, metadata, and legal links.",
    "variants": [
      "simple",
      "columns",
      "product"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<footer class=\"sk-footer\"><div class=\"sk-footer__inner\"><p>SiteKit</p><nav aria-label=\"Footer\"><a href=\"#main\">Documentation</a></nav><small>SiteKit · MIT</small></div></footer>\n"
  },
  {
    "slug": "form",
    "name": "Form",
    "category": "Forms",
    "description": "A semantic form layout for labeled controls and actions.",
    "variants": [
      "stacked",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<form class=\"sk-form\"><label for=\"form-email\">Email</label><input id=\"form-email\" name=\"email\" type=\"email\" autocomplete=\"email\" placeholder=\"you@example.com\"><label for=\"form-message\">Message</label><textarea id=\"form-message\" name=\"message\">Tell us what you need.</textarea><button class=\"sk-button\" type=\"submit\">Submit</button></form>\n"
  },
  {
    "slug": "form-field",
    "name": "Form Field",
    "category": "Forms",
    "description": "A labeled input group with help, validation, and autocomplete support.",
    "variants": [
      "text",
      "select",
      "textarea",
      "checkbox"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-form-field\"><label for=\"demo-form-field\">Form Field</label><input id=\"demo-form-field\" name=\"project\" type=\"text\" aria-describedby=\"demo-form-field-help\"><p class=\"sk-form-field__help\" id=\"demo-form-field-help\">Use a short project name.</p></div>\n"
  },
  {
    "slug": "generator-panel",
    "name": "Generator Panel",
    "category": "Tools",
    "description": "A form-forward tool panel for small generators, prompts, and preview controls.",
    "variants": [
      "form-preview",
      "compact",
      "stacked"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-component-container\"><section class=\"sk-generator-panel\" aria-labelledby=\"generator-title\">\n  <form>\n    <h2 id=\"generator-title\">Thumbnail generator</h2>\n    <label for=\"generator-topic\">Topic</label>\n    <input id=\"generator-topic\" name=\"topic\" type=\"text\" value=\"Static site launch\">\n    <label for=\"generator-style\">Style</label>\n    <select id=\"generator-style\" name=\"style\"><option>Editorial</option><option>Technical</option></select>\n    <button class=\"sk-button\" type=\"submit\">Generate</button>\n  </form>\n  <div class=\"sk-generator-panel__preview\" role=\"img\" aria-label=\"Generated preview placeholder\">Preview</div>\n</section></div>\n"
  },
  {
    "slug": "header",
    "name": "Header",
    "category": "Navigation",
    "description": "A top-level site header with navigation and primary action.",
    "variants": [
      "default",
      "docs",
      "commerce"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<header class=\"sk-header\"><div class=\"sk-header__inner\"><a href=\"/\" aria-label=\"SiteKit home\">SiteKit</a><nav aria-label=\"Primary\"><a href=\"#main\">Overview</a></nav><div class=\"sk-header__actions\"><button class=\"sk-button\" type=\"button\">Continue</button></div></div></header>\n"
  },
  {
    "slug": "heading",
    "name": "Heading",
    "category": "Foundations",
    "description": "A typographic heading pattern with optional supporting text.",
    "variants": [
      "section",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<header class=\"sk-heading\"><p>Section</p><h2>Build with clear hierarchy.</h2><span>Supporting metadata stays compact and readable.</span></header>\n"
  },
  {
    "slug": "hero",
    "name": "Hero",
    "category": "Content",
    "description": "A first-viewport introduction for product, documentation, and launch pages.",
    "variants": [
      "split",
      "centered",
      "technical"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<section class=\"sk-hero\" aria-labelledby=\"hero-title\"><div class=\"sk-hero__inner\"><h2 id=\"hero-title\">Build with SiteKit</h2><p>Semantic HTML, local assets, and reusable styles.</p><div class=\"sk-hero__actions\"><button class=\"sk-button\" type=\"button\">Continue</button></div></div></section>\n"
  },
  {
    "slug": "icon",
    "name": "Icon",
    "category": "Foundations",
    "description": "A small symbolic marker with an accessible name when meaningful.",
    "variants": [
      "line",
      "compact",
      "decorative",
      "meaningful",
      "inline",
      "external"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<span class=\"sk-icon\" data-icon-name=\"check\" role=\"img\" aria-label=\"Confirmed\"><svg aria-hidden=\"true\" viewBox=\"0 0 24 24\" focusable=\"false\"><path d=\"m5 12 4 4L19 6\" /></svg></span>\n"
  },
  {
    "slug": "image",
    "name": "Image",
    "category": "Data Display",
    "description": "A responsive image frame with optional caption.",
    "variants": [
      "figure",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<figure class=\"sk-image\"><div role=\"img\" aria-label=\"SiteKit placeholder image\">Image</div><figcaption>Tokenized image frame</figcaption></figure>\n"
  },
  {
    "slug": "label",
    "name": "Label",
    "category": "Forms",
    "description": "A compact text label for form fields or metadata.",
    "variants": [
      "field",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<label class=\"sk-label\" for=\"label-example\">Project name</label>\n<input id=\"label-example\" name=\"project\" type=\"text\">\n"
  },
  {
    "slug": "link",
    "name": "Link",
    "category": "Foundations",
    "description": "A text link with visible focus and hover states.",
    "variants": [
      "inline",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<a class=\"sk-link\" href=\"#components\">Read component docs</a>\n"
  },
  {
    "slug": "list",
    "name": "List",
    "category": "Data Display",
    "description": "A semantic ordered or unordered list with consistent spacing.",
    "variants": [
      "unordered",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<ul class=\"sk-list\"><li>Semantic markup</li><li>Tokenized spacing</li><li>Readable hierarchy</li></ul>\n"
  },
  {
    "slug": "metadata-panel",
    "name": "Metadata Panel",
    "category": "Data Display",
    "description": "A compact key-value panel for operational metadata and object facts.",
    "variants": [
      "default",
      "compact",
      "sidecar"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<aside class=\"sk-metadata-panel\" aria-label=\"Metadata Panel\"><dl><div><dt>Version</dt><dd>1.0.0</dd></div></dl></aside>\n"
  },
  {
    "slug": "modal",
    "name": "Modal",
    "category": "Overlays",
    "description": "An interruptive dialog that requires deliberate focus management.",
    "variants": [
      "default",
      "danger",
      "wide"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<button class=\"sk-button\" type=\"button\" data-sk-modal-open=\"demo-modal\">Open Review changes</button><dialog class=\"sk-modal\" data-sk-modal id=\"demo-modal\" tabindex=\"-1\" aria-labelledby=\"demo-modal-title\"><h2 id=\"demo-modal-title\">Review changes</h2><div>Semantic HTML, local assets, and reusable styles.</div><form method=\"dialog\" class=\"sk-modal__actions\"><button class=\"sk-button\" type=\"submit\" data-sk-modal-close data-variant=\"secondary\">Close</button><button class=\"sk-button\" type=\"button\">Continue</button></form></dialog>\n"
  },
  {
    "slug": "navigation",
    "name": "Navigation",
    "category": "Navigation",
    "description": "A semantic navigation region for primary or secondary links.",
    "variants": [
      "primary",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<nav class=\"sk-navigation\" aria-label=\"Primary\"><a href=\"#components\">Components</a><a href=\"#tokens\">Tokens</a><a href=\"#recipes\">Recipes</a></nav>\n"
  },
  {
    "slug": "newsletter-signup",
    "name": "Newsletter Signup",
    "category": "Content",
    "description": "A focused email capture block with semantic form controls and compact supporting copy.",
    "variants": [
      "inline",
      "boxed",
      "modal",
      "split"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-component-container\"><section class=\"sk-newsletter-signup\" aria-labelledby=\"newsletter-title\">\n  <div class=\"sk-newsletter-signup__copy\">\n    <span class=\"sk-badge\" data-variant=\"outline\">Newsletter</span>\n    <h2 id=\"newsletter-title\">Stay in the loop.</h2>\n    <p>Get concise build notes, release prompts, and design-system updates.</p>\n  </div>\n  <form class=\"sk-newsletter-signup__form\">\n    <label for=\"newsletter-email\">Email address</label>\n    <div>\n      <input id=\"newsletter-email\" name=\"email\" type=\"email\" autocomplete=\"email\" placeholder=\"you@example.com\">\n      <button class=\"sk-button\" type=\"submit\">Subscribe</button>\n    </div>\n    <p>One useful note at a time. No feed noise.</p>\n  </form>\n</section></div>\n"
  },
  {
    "slug": "pagination",
    "name": "Pagination",
    "category": "Actions",
    "description": "A page navigation control for long result sets.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<nav class=\"sk-pagination\" aria-label=\"Pagination\"><a href=\"#prev\">Prev</a><a aria-current=\"page\" href=\"#1\">1</a><a href=\"#2\">2</a><a href=\"#next\">Next</a></nav>\n"
  },
  {
    "slug": "partners-strip",
    "name": "Partners Strip",
    "category": "Content",
    "description": "A logo or partner proof row with semantic list structure and theme-safe styling.",
    "variants": [
      "logos",
      "boxed",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-partners-strip\" aria-labelledby=\"partners-title\">\n  <h2 id=\"partners-title\">Trusted by leading teams</h2>\n  <ul>\n    <li>Northstar</li>\n    <li>Atlas</li>\n    <li>Signal</li>\n    <li>Foundry</li>\n  </ul>\n</section>\n"
  },
  {
    "slug": "popover",
    "name": "Popover",
    "category": "Overlays",
    "description": "A small contextual surface anchored to a trigger.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-popover\"><button class=\"sk-button\" type=\"button\" aria-expanded=\"false\">Details</button><div role=\"dialog\" aria-label=\"Details popover\" hidden><p>Compact contextual information.</p></div></div>\n"
  },
  {
    "slug": "pricing-table",
    "name": "Pricing Table",
    "category": "Commerce",
    "description": "A commercial pricing comparison layout with plans and features.",
    "variants": [
      "monthly",
      "annual",
      "comparison"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-pricing-table\"><table><caption>Plan comparison</caption><thead><tr><th scope=\"col\">Feature</th><th scope=\"col\">Starter</th><th scope=\"col\">Pro</th><th scope=\"col\">Scale</th></tr></thead><tbody><tr><th scope=\"row\">Monthly price</th><td data-price>$19</td><td data-price>$49</td><td data-price>$99</td></tr><tr><th scope=\"row\">Projects</th><td>3</td><td>25</td><td>Unlimited</td></tr><tr><th scope=\"row\">Components</th><td>Core</td><td>Core + commerce</td><td>Everything</td></tr><tr><th scope=\"row\">Support</th><td>Email</td><td>Priority</td><td>Dedicated channel</td></tr></tbody></table></div>\n"
  },
  {
    "slug": "product-card",
    "name": "Product Card",
    "category": "Commerce",
    "description": "A semantic commerce product summary with media, price, and actions.",
    "variants": [
      "default",
      "compact",
      "featured"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-product-card\" aria-labelledby=\"product-card-title\"><div class=\"sk-product-card__layout\"><div><h2 id=\"product-card-title\">SiteKit Pro</h2><p>Reusable component contracts, lab previews, and commerce-ready sections.</p><p class=\"sk-product-card__price\">$49</p><div class=\"sk-product-card__actions\"><button class=\"sk-button\" type=\"button\">Continue</button></div></div><div data-product-media aria-hidden=\"true\">Product</div></div></section>\n"
  },
  {
    "slug": "product-grid",
    "name": "Product Grid",
    "category": "Commerce",
    "description": "A responsive product listing surface.",
    "variants": [
      "catalog",
      "compact",
      "comparison"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<section class=\"sk-product-grid\" aria-label=\"Products\"><article><div data-product-media>Preview</div><h3>Starter Kit</h3><p>$49</p><button class=\"sk-button\" type=\"button\">Add</button></article><article><div data-product-media>Preview</div><h3>Pro Kit</h3><p>$99</p><button class=\"sk-button\" type=\"button\">Add</button></article><article><div data-product-media>Preview</div><h3>Team Kit</h3><p>$149</p><button class=\"sk-button\" type=\"button\">Add</button></article></section>\n"
  },
  {
    "slug": "product-showcase",
    "name": "Product Showcase",
    "category": "Commerce",
    "description": "A compact commerce or template showcase adapted from legacy landing-page demos.",
    "variants": [
      "template",
      "commerce",
      "editorial"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-component-container\"><section class=\"sk-product-showcase\" aria-labelledby=\"product-showcase-title\">\n  <div class=\"sk-product-showcase__intro\">\n    <span class=\"sk-badge\" data-variant=\"outline\">Featured</span>\n    <h2 id=\"product-showcase-title\">Launch System Pro</h2>\n    <p>A focused product showcase with a clear hero object, benefits, and supporting offers.</p>\n    <a class=\"sk-button\" href=\"#product-showcase-title\">View product</a>\n  </div>\n  <div class=\"sk-product-showcase__hero\" role=\"img\" aria-label=\"Launch System Pro product preview\">Product preview</div>\n  <div class=\"sk-product-showcase__items\">\n    <article><h3>Included templates</h3><p>Landing, docs, pricing, and ecommerce sections.</p></article>\n    <article><h3>Team license</h3><p>Use across production launches and client builds.</p></article>\n  </div>\n</section></div>\n"
  },
  {
    "slug": "progress-bar",
    "name": "Progress Bar",
    "category": "Feedback",
    "description": "A horizontal progress meter for determinate completion.",
    "variants": [
      "determinate",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<label for=\"build-progress\">Build progress</label><progress class=\"sk-progress-bar\" id=\"build-progress\" max=\"100\" value=\"64\">64%</progress>\n"
  },
  {
    "slug": "progress-indicator",
    "name": "Progress Indicator",
    "category": "Feedback",
    "description": "A compact step or status indicator for multi-step flows.",
    "variants": [
      "steps",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<ol class=\"sk-progress-indicator\" aria-label=\"Progress\"><li data-complete>Plan</li><li data-current>Build</li><li>Ship</li></ol>\n"
  },
  {
    "slug": "promo-banner",
    "name": "Promo Banner",
    "category": "Commerce",
    "description": "A dismissible commercial or release announcement banner.",
    "variants": [
      "info",
      "success",
      "warning"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-promo-banner\" aria-labelledby=\"promo-banner-title\"><div class=\"sk-promo-banner__copy\"><h2 id=\"promo-banner-title\">Launch week bundle</h2><p>Save 20% on templates, components, and deployment recipes.</p></div><div class=\"sk-promo-banner__actions\"><button class=\"sk-button\" type=\"button\">Continue</button><button type=\"button\" data-sk-dismiss aria-label=\"Dismiss announcement\">Close</button></div></section>\n"
  },
  {
    "slug": "quote",
    "name": "Quote",
    "category": "Content",
    "description": "A pull quote or testimonial block with citation.",
    "variants": [
      "pull",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<figure class=\"sk-quote\"><blockquote>SiteKit keeps interface patterns inspectable and reusable.</blockquote><figcaption>Product team</figcaption></figure>\n"
  },
  {
    "slug": "radio-button",
    "name": "Radio Button",
    "category": "Forms",
    "description": "A single-choice input within a related option group.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<fieldset class=\"sk-radio-button\"><legend>Plan</legend><label><input type=\"radio\" name=\"plan\" checked> Starter</label><label><input type=\"radio\" name=\"plan\"> Pro</label></fieldset>\n"
  },
  {
    "slug": "rating",
    "name": "Rating",
    "category": "Data Display",
    "description": "A rating display or input for qualitative feedback.",
    "variants": [
      "five-point",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-rating\" role=\"img\" aria-label=\"4 out of 5 stars\"><span>★</span><span>★</span><span>★</span><span>★</span><span>☆</span></div>\n"
  },
  {
    "slug": "recent-posts",
    "name": "Recent Posts",
    "category": "Content",
    "description": "A semantic article-list component for blog previews and latest insights.",
    "variants": [
      "cards",
      "list",
      "featured"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-recent-posts\" aria-labelledby=\"recent-posts-title\">\n  <h2 id=\"recent-posts-title\">Latest insights</h2>\n  <div>\n    <article><p class=\"sk-recent-posts__meta\">Guide</p><h3><a href=\"#recent-posts-title\">How SiteKit keeps components consistent</a></h3><p>Source contracts, generated CSS, and previews stay connected.</p></article>\n    <article><p class=\"sk-recent-posts__meta\">Workflow</p><h3><a href=\"#recent-posts-title\">Migrating legacy patterns cleanly</a></h3><p>Use old layouts as source material, not visual drift.</p></article>\n  </div>\n</section>\n"
  },
  {
    "slug": "resource-links",
    "name": "Resource Links",
    "category": "Content",
    "description": "A compact link collection for docs, examples, templates, and external references.",
    "variants": [
      "grid",
      "stack",
      "annotated"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-resource-links\" aria-labelledby=\"resources-title\">\n  <h2 id=\"resources-title\">Resource links</h2>\n  <ul>\n    <li><a href=\"#resources-title\">Starter docs</a><p>Implementation notes and source contracts.</p></li>\n    <li><a href=\"#resources-title\">Component recipes</a><p>Composable page patterns.</p></li>\n    <li><a href=\"#resources-title\">Validation guide</a><p>Build, lint, and snapshot checks.</p></li>\n  </ul>\n</section>\n"
  },
  {
    "slug": "rich-text-editor",
    "name": "Rich Text Editor",
    "category": "Forms",
    "description": "A text editing surface with formatting controls.",
    "variants": [
      "basic",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-rich-text-editor\" aria-labelledby=\"rte-title\"><h2 id=\"rte-title\">Editor</h2><div hidden role=\"toolbar\" aria-label=\"Formatting\"><button type=\"button\" aria-label=\"Bold\">B</button><button type=\"button\" aria-label=\"Italic\">I</button><button type=\"button\" aria-label=\"Insert link\">Link</button></div><div contenteditable=\"true\" role=\"textbox\" aria-label=\"Content\" aria-multiline=\"true\">Write content here.</div></section>\n"
  },
  {
    "slug": "roadmap",
    "name": "Roadmap",
    "category": "Data Display",
    "description": "A chronological product timeline for milestones, launches, and upcoming work.",
    "variants": [
      "timeline",
      "compact",
      "release-plan"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-roadmap\" aria-labelledby=\"roadmap-title\">\n  <h2 id=\"roadmap-title\">Product roadmap</h2>\n  <ol>\n    <li><time datetime=\"2026-07\">Jul 2026</time><h3>Component import</h3><p>Legacy marketing patterns become token-driven SiteKit components.</p></li>\n    <li><time datetime=\"2026-08\">Aug 2026</time><h3>Recipe refresh</h3><p>Recipes consume the expanded component set.</p></li>\n    <li><time datetime=\"2026-09\">Sep 2026</time><h3>Snapshot review</h3><p>Visual baselines cover the full catalog.</p></li>\n  </ol>\n</section>\n"
  },
  {
    "slug": "search-input",
    "name": "Search Input",
    "category": "Forms",
    "description": "A search field with a visible submit action.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<form class=\"sk-search-input\" role=\"search\"><label for=\"search-input-control\">Search</label><div><input id=\"search-input-control\" type=\"search\" value=\"components\"><button class=\"sk-button\" type=\"submit\">Search</button></div></form>\n"
  },
  {
    "slug": "segmented-control",
    "name": "Segmented Control",
    "category": "Actions",
    "description": "A compact grouped control for switching modes.",
    "variants": [
      "single-select",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-segmented-control\" role=\"group\" aria-label=\"View mode\"><button type=\"button\" aria-pressed=\"true\">Grid</button><button type=\"button\">List</button><button type=\"button\">Table</button></div>\n"
  },
  {
    "slug": "select",
    "name": "Select",
    "category": "Forms",
    "description": "A native select control with label and options.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-select\"><label for=\"select-control\">Theme</label><select id=\"select-control\"><option>kujo-light</option><option>kujo-dark</option><option>personal-dark</option></select></div>\n"
  },
  {
    "slug": "separator",
    "name": "Separator",
    "category": "Foundations",
    "description": "A semantic visual divider between related sections.",
    "variants": [
      "horizontal",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-separator\" role=\"separator\" aria-orientation=\"horizontal\"><span aria-hidden=\"true\">X</span></div>\n"
  },
  {
    "slug": "skeleton",
    "name": "Skeleton",
    "category": "Feedback",
    "description": "A placeholder surface that indicates loading content.",
    "variants": [
      "text",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-skeleton\" aria-hidden=\"true\"><span class=\"sk-skeleton__media\"></span><span></span><span></span><span></span></div>\n"
  },
  {
    "slug": "skip-link",
    "name": "Skip Link",
    "category": "Foundations",
    "description": "An accessible link for skipping directly to page content.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<a class=\"sk-skip-link\" href=\"#main\">Skip to main content</a>\n<main id=\"main\" tabindex=\"-1\"><h1>Page content</h1></main>\n"
  },
  {
    "slug": "slider",
    "name": "Slider",
    "category": "Forms",
    "description": "A range input for selecting a numeric value.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-slider\"><label for=\"slider-control\">Intensity</label><input id=\"slider-control\" type=\"range\" min=\"0\" max=\"100\" value=\"64\"></div>\n"
  },
  {
    "slug": "spinner",
    "name": "Spinner",
    "category": "Feedback",
    "description": "A compact indeterminate loading indicator.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-spinner\" role=\"status\"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span class=\"sk-sr-only\">Loading</span></div>\n"
  },
  {
    "slug": "stack",
    "name": "Stack",
    "category": "Content",
    "description": "A vertical layout primitive for consistent spacing.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-stack-component\"><div>First item</div><div>Second item</div><div>Third item</div></div>\n"
  },
  {
    "slug": "stats-bar",
    "name": "Stats Bar",
    "category": "Data Display",
    "description": "A semantic metric strip for proof points, performance numbers, or portfolio counters.",
    "variants": [
      "inline",
      "boxed",
      "stacked"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-stats-bar\" aria-label=\"Project stats\">\n  <dl>\n    <div><dt>Open Source Plugins</dt><dd>50+</dd></div>\n    <div><dt>Years Experience</dt><dd>20+</dd></div>\n    <div><dt>Lighthouse Scores</dt><dd>100%</dd></div>\n  </dl>\n</section>\n"
  },
  {
    "slug": "stepper",
    "name": "Stepper",
    "category": "Forms",
    "description": "A numeric input with increment and decrement actions.",
    "variants": [
      "number",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-stepper\"><label for=\"stepper-control\">Seats</label><div><button type=\"button\">−</button><input id=\"stepper-control\" type=\"number\" value=\"3\"><button type=\"button\">+</button></div></div>\n"
  },
  {
    "slug": "table",
    "name": "Table",
    "category": "Data Display",
    "description": "A semantic table for structured comparison or tabular data.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-table\"><table><caption>Release QA queue</caption><thead><tr><th scope=\"col\">Area</th><th scope=\"col\">Owner</th><th scope=\"col\">Status</th><th scope=\"col\">Due</th></tr></thead><tbody><tr><th scope=\"row\">Checkout flow</th><td>Design Systems</td><td>In review</td><td>Jul 12</td></tr><tr><th scope=\"row\">Account drawer</th><td>Frontend</td><td>Ready</td><td>Jul 14</td></tr><tr><th scope=\"row\">Email capture</th><td>Growth</td><td>Needs copy</td><td>Jul 15</td></tr></tbody></table></div>\n"
  },
  {
    "slug": "tabs",
    "name": "Tabs",
    "category": "Navigation",
    "description": "A keyboard navigable view switcher for related panels.",
    "variants": [
      "line",
      "boxed",
      "docs"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-tabs\"><div role=\"tablist\" aria-label=\"Tabs\"><button id=\"demo-tabs-0\" type=\"button\" role=\"tab\" aria-controls=\"demo-tabs-panel-0\" aria-selected=\"true\">Overview</button><button id=\"demo-tabs-1\" type=\"button\" role=\"tab\" aria-controls=\"demo-tabs-panel-1\" aria-selected=\"false\">Details</button></div><section id=\"demo-tabs-panel-0\" role=\"tabpanel\" aria-labelledby=\"demo-tabs-0\" tabindex=\"0\"><p>Overview content.</p></section><section id=\"demo-tabs-panel-1\" role=\"tabpanel\" aria-labelledby=\"demo-tabs-1\" tabindex=\"0\"><p>Details content.</p></section></div>\n"
  },
  {
    "slug": "team-grid",
    "name": "Team Grid",
    "category": "Content",
    "description": "A responsive people grid for profiles, roles, and compact bios.",
    "variants": [
      "profiles",
      "compact",
      "leadership"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-team-grid\" aria-labelledby=\"team-title\">\n  <h2 id=\"team-title\">Meet the team</h2>\n  <ul>\n    <li><span aria-hidden=\"true\">AM</span><h3>Alexandra Morgan</h3><p>Product strategy</p></li>\n    <li><span aria-hidden=\"true\">MP</span><h3>Michael Patel</h3><p>Engineering systems</p></li>\n    <li><span aria-hidden=\"true\">JR</span><h3>Jamie Rivera</h3><p>Design operations</p></li>\n  </ul>\n</section>\n"
  },
  {
    "slug": "testimonial-rail",
    "name": "Testimonial Rail",
    "category": "Content",
    "description": "A scroll-safe testimonial layout for customer quotes and builder proof.",
    "variants": [
      "rail",
      "grid",
      "featured"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-testimonial-rail\" aria-labelledby=\"testimonial-title\">\n  <h2 id=\"testimonial-title\">What builders say</h2>\n  <div>\n    <figure><blockquote>SiteKit gave our launch pages a consistent system without slowing the team down.</blockquote><figcaption>Alex, product lead</figcaption></figure>\n    <figure><blockquote>The components are plain enough to trust and structured enough to scale.</blockquote><figcaption>Morgan, engineer</figcaption></figure>\n  </div>\n</section>\n"
  },
  {
    "slug": "text-input",
    "name": "Text Input",
    "category": "Forms",
    "description": "A single-line text input with a visible label.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-text-input\"><label for=\"text-input-control\">Project</label><input id=\"text-input-control\" type=\"text\" value=\"SiteKit\"></div>\n"
  },
  {
    "slug": "textarea",
    "name": "Textarea",
    "category": "Forms",
    "description": "A multi-line text input with label and help text.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<div class=\"sk-textarea\"><label for=\"textarea-control\">Notes</label><textarea id=\"textarea-control\">Document implementation details.</textarea></div>\n"
  },
  {
    "slug": "toast",
    "name": "Toast",
    "category": "Feedback",
    "description": "A non-modal notification for transient feedback.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<section class=\"sk-toast\" role=\"status\"><strong>Saved</strong><p>Your changes are synced.</p><button type=\"button\" aria-label=\"Dismiss\" data-sk-dismiss>X</button></section>\n"
  },
  {
    "slug": "toggle",
    "name": "Toggle",
    "category": "Forms",
    "description": "A binary switch-style control using a native checkbox.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<label class=\"sk-toggle\"><input type=\"checkbox\" checked><span>Enable notifications</span></label>\n"
  },
  {
    "slug": "tooltip",
    "name": "Tooltip",
    "category": "Overlays",
    "description": "A short contextual text hint for an adjacent control.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<span class=\"sk-tooltip\"><button class=\"sk-button\" type=\"button\" aria-describedby=\"tooltip-content\" aria-expanded=\"false\">Info</button><span id=\"tooltip-content\" role=\"tooltip\" hidden>Helpful context for this control.</span></span>\n"
  },
  {
    "slug": "tree-view",
    "name": "Tree View",
    "category": "Navigation",
    "description": "A hierarchical navigation or selection tree.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<nav class=\"sk-tree-view\" aria-label=\"Component tree\"><ul><li><button type=\"button\" aria-expanded=\"true\">Inputs</button><ul><li><a href=\"#text-input\">Text input</a></li><li><a href=\"#select\">Select</a></li></ul></li></ul></nav>\n"
  },
  {
    "slug": "trust-strip",
    "name": "Trust Strip",
    "category": "Commerce",
    "description": "A compact proof row for security, shipping, warranties, or social proof.",
    "variants": [
      "default",
      "compact",
      "bordered"
    ],
    "keyboard": "No keyboard behavior required unless interactive content is slotted.",
    "sample": "<section class=\"sk-trust-strip\" aria-labelledby=\"trust-strip-title\"><h2 id=\"trust-strip-title\">Trusted delivery signals</h2><ul><li><strong>SSL</strong><span>Secure checkout</span></li><li><strong>24h</strong><span>Response window</span></li><li><strong>99.9%</strong><span>Uptime target</span></li><li><strong>30d</strong><span>Refund policy</span></li></ul></section>\n"
  },
  {
    "slug": "video",
    "name": "Video",
    "category": "Data Display",
    "description": "A responsive video embed frame with caption.",
    "variants": [
      "embed",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<figure class=\"sk-video\"><div role=\"img\" aria-label=\"Video preview\">16:9 Video</div><figcaption>Accessible video frame with caption.</figcaption></figure>\n"
  },
  {
    "slug": "visually-hidden",
    "name": "Visually Hidden",
    "category": "Foundations",
    "description": "A utility wrapper for content available to assistive technology only.",
    "variants": [
      "default",
      "compact"
    ],
    "keyboard": "Interactive descendants must be reachable by keyboard and expose visible focus.",
    "sample": "<p class=\"sk-visually-hidden\">This text is available to screen readers.</p><p aria-hidden=\"true\">Visible companion text.</p>\n"
  }
];
